import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// normal = 400
// medium = 500
// semibold = 600
// bold = 700


const inter = Inter({ 
  subsets: ['latin'],
  weight: ['400', '600'] ,
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>{children}</body>
    </html>
  )
}
